// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/danmaku.dart';
import 'api/extractor.dart';
import 'api/simple.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SliveBilibiliDanmakuProviderPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliDanmakuProvider;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SliveBilibiliExtractorPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliExtractor;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SliveDanmuConnectionPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDanmuConnection;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SliveDouyinDanmakuProviderPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinDanmakuProvider;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SliveDouyinExtractorPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinExtractor;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SliveDouyuDanmakuProviderPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuDanmakuProvider;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SliveDouyuExtractorPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuExtractor;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SliveHuyaDanmakuProviderPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaDanmakuProvider;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SliveHuyaExtractorPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaExtractor;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SliveTwitchDanmakuProviderPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchDanmakuProvider;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SliveTwitchExtractorPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchExtractor;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  SliveBilibiliDanmakuProvider
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliDanmakuProvider(
    dynamic raw,
  );

  @protected
  SliveBilibiliExtractor
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliExtractor(
    dynamic raw,
  );

  @protected
  SliveDanmuConnection
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDanmuConnection(
    dynamic raw,
  );

  @protected
  SliveDouyinDanmakuProvider
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinDanmakuProvider(
    dynamic raw,
  );

  @protected
  SliveDouyinExtractor
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinExtractor(
    dynamic raw,
  );

  @protected
  SliveDouyuDanmakuProvider
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuDanmakuProvider(
    dynamic raw,
  );

  @protected
  SliveDouyuExtractor
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuExtractor(
    dynamic raw,
  );

  @protected
  SliveHuyaDanmakuProvider
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaDanmakuProvider(
    dynamic raw,
  );

  @protected
  SliveHuyaExtractor
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaExtractor(
    dynamic raw,
  );

  @protected
  SliveTwitchDanmakuProvider
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchDanmakuProvider(
    dynamic raw,
  );

  @protected
  SliveTwitchExtractor
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchExtractor(
    dynamic raw,
  );

  @protected
  SliveDanmuConnection
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDanmuConnection(
    dynamic raw,
  );

  @protected
  SliveBilibiliDanmakuProvider
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliDanmakuProvider(
    dynamic raw,
  );

  @protected
  SliveBilibiliExtractor
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliExtractor(
    dynamic raw,
  );

  @protected
  SliveDanmuConnection
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDanmuConnection(
    dynamic raw,
  );

  @protected
  SliveDouyinDanmakuProvider
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinDanmakuProvider(
    dynamic raw,
  );

  @protected
  SliveDouyinExtractor
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinExtractor(
    dynamic raw,
  );

  @protected
  SliveDouyuDanmakuProvider
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuDanmakuProvider(
    dynamic raw,
  );

  @protected
  SliveDouyuExtractor
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuExtractor(
    dynamic raw,
  );

  @protected
  SliveHuyaDanmakuProvider
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaDanmakuProvider(
    dynamic raw,
  );

  @protected
  SliveHuyaExtractor
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaExtractor(
    dynamic raw,
  );

  @protected
  SliveTwitchDanmakuProvider
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchDanmakuProvider(
    dynamic raw,
  );

  @protected
  SliveTwitchExtractor
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchExtractor(
    dynamic raw,
  );

  @protected
  SliveBilibiliDanmakuProvider
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliDanmakuProvider(
    dynamic raw,
  );

  @protected
  SliveBilibiliExtractor
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliExtractor(
    dynamic raw,
  );

  @protected
  SliveDanmuConnection
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDanmuConnection(
    dynamic raw,
  );

  @protected
  SliveDouyinDanmakuProvider
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinDanmakuProvider(
    dynamic raw,
  );

  @protected
  SliveDouyinExtractor
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinExtractor(
    dynamic raw,
  );

  @protected
  SliveDouyuDanmakuProvider
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuDanmakuProvider(
    dynamic raw,
  );

  @protected
  SliveDouyuExtractor
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuExtractor(
    dynamic raw,
  );

  @protected
  SliveHuyaDanmakuProvider
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaDanmakuProvider(
    dynamic raw,
  );

  @protected
  SliveHuyaExtractor
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaExtractor(
    dynamic raw,
  );

  @protected
  SliveTwitchDanmakuProvider
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchDanmakuProvider(
    dynamic raw,
  );

  @protected
  SliveTwitchExtractor
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchExtractor(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  SliveDanmuControlEvent dco_decode_box_autoadd_slive_danmu_control_event(
    dynamic raw,
  );

  @protected
  SliveDanmuItem dco_decode_box_autoadd_slive_danmu_item(dynamic raw);

  @protected
  SliveMessage dco_decode_box_autoadd_slive_message(dynamic raw);

  @protected
  SlivePlayQuality dco_decode_box_autoadd_slive_play_quality(dynamic raw);

  @protected
  SliveRoomDetail dco_decode_box_autoadd_slive_room_detail(dynamic raw);

  @protected
  SliveSubCategory dco_decode_box_autoadd_slive_sub_category(dynamic raw);

  @protected
  SliveSuperChatMessage dco_decode_box_autoadd_slive_super_chat_message(
    dynamic raw,
  );

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SliveAnchorItem> dco_decode_list_slive_anchor_item(dynamic raw);

  @protected
  List<SliveCategory> dco_decode_list_slive_category(dynamic raw);

  @protected
  List<SliveMapEntry> dco_decode_list_slive_map_entry(dynamic raw);

  @protected
  List<SlivePlayQuality> dco_decode_list_slive_play_quality(dynamic raw);

  @protected
  List<SliveRoomItem> dco_decode_list_slive_room_item(dynamic raw);

  @protected
  List<SliveSubCategory> dco_decode_list_slive_sub_category(dynamic raw);

  @protected
  List<SliveSuperChatMessage> dco_decode_list_slive_super_chat_message(
    dynamic raw,
  );

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  SliveDanmuItem? dco_decode_opt_box_autoadd_slive_danmu_item(dynamic raw);

  @protected
  List<SliveMapEntry>? dco_decode_opt_list_slive_map_entry(dynamic raw);

  @protected
  SliveAnchorItem dco_decode_slive_anchor_item(dynamic raw);

  @protected
  SliveCategory dco_decode_slive_category(dynamic raw);

  @protected
  SliveCategoryResult dco_decode_slive_category_result(dynamic raw);

  @protected
  SliveDanmuControlEvent dco_decode_slive_danmu_control_event(dynamic raw);

  @protected
  SliveDanmuItem dco_decode_slive_danmu_item(dynamic raw);

  @protected
  SliveMapEntry dco_decode_slive_map_entry(dynamic raw);

  @protected
  SliveMessage dco_decode_slive_message(dynamic raw);

  @protected
  SliveMessageColor dco_decode_slive_message_color(dynamic raw);

  @protected
  SliveMessageType dco_decode_slive_message_type(dynamic raw);

  @protected
  SlivePlayQuality dco_decode_slive_play_quality(dynamic raw);

  @protected
  SlivePlayUrl dco_decode_slive_play_url(dynamic raw);

  @protected
  SliveRoomDetail dco_decode_slive_room_detail(dynamic raw);

  @protected
  SliveRoomItem dco_decode_slive_room_item(dynamic raw);

  @protected
  SliveSearchAnchorResult dco_decode_slive_search_anchor_result(dynamic raw);

  @protected
  SliveSearchRoomResult dco_decode_slive_search_room_result(dynamic raw);

  @protected
  SliveSubCategory dco_decode_slive_sub_category(dynamic raw);

  @protected
  SliveSuperChatMessage dco_decode_slive_super_chat_message(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  SliveBilibiliDanmakuProvider
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  SliveBilibiliExtractor
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliExtractor(
    SseDeserializer deserializer,
  );

  @protected
  SliveDanmuConnection
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDanmuConnection(
    SseDeserializer deserializer,
  );

  @protected
  SliveDouyinDanmakuProvider
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  SliveDouyinExtractor
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinExtractor(
    SseDeserializer deserializer,
  );

  @protected
  SliveDouyuDanmakuProvider
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  SliveDouyuExtractor
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuExtractor(
    SseDeserializer deserializer,
  );

  @protected
  SliveHuyaDanmakuProvider
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  SliveHuyaExtractor
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaExtractor(
    SseDeserializer deserializer,
  );

  @protected
  SliveTwitchDanmakuProvider
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  SliveTwitchExtractor
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchExtractor(
    SseDeserializer deserializer,
  );

  @protected
  SliveDanmuConnection
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDanmuConnection(
    SseDeserializer deserializer,
  );

  @protected
  SliveBilibiliDanmakuProvider
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  SliveBilibiliExtractor
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliExtractor(
    SseDeserializer deserializer,
  );

  @protected
  SliveDanmuConnection
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDanmuConnection(
    SseDeserializer deserializer,
  );

  @protected
  SliveDouyinDanmakuProvider
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  SliveDouyinExtractor
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinExtractor(
    SseDeserializer deserializer,
  );

  @protected
  SliveDouyuDanmakuProvider
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  SliveDouyuExtractor
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuExtractor(
    SseDeserializer deserializer,
  );

  @protected
  SliveHuyaDanmakuProvider
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  SliveHuyaExtractor
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaExtractor(
    SseDeserializer deserializer,
  );

  @protected
  SliveTwitchDanmakuProvider
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  SliveTwitchExtractor
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchExtractor(
    SseDeserializer deserializer,
  );

  @protected
  SliveBilibiliDanmakuProvider
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  SliveBilibiliExtractor
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliExtractor(
    SseDeserializer deserializer,
  );

  @protected
  SliveDanmuConnection
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDanmuConnection(
    SseDeserializer deserializer,
  );

  @protected
  SliveDouyinDanmakuProvider
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  SliveDouyinExtractor
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinExtractor(
    SseDeserializer deserializer,
  );

  @protected
  SliveDouyuDanmakuProvider
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  SliveDouyuExtractor
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuExtractor(
    SseDeserializer deserializer,
  );

  @protected
  SliveHuyaDanmakuProvider
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  SliveHuyaExtractor
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaExtractor(
    SseDeserializer deserializer,
  );

  @protected
  SliveTwitchDanmakuProvider
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  SliveTwitchExtractor
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchExtractor(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  SliveDanmuControlEvent sse_decode_box_autoadd_slive_danmu_control_event(
    SseDeserializer deserializer,
  );

  @protected
  SliveDanmuItem sse_decode_box_autoadd_slive_danmu_item(
    SseDeserializer deserializer,
  );

  @protected
  SliveMessage sse_decode_box_autoadd_slive_message(
    SseDeserializer deserializer,
  );

  @protected
  SlivePlayQuality sse_decode_box_autoadd_slive_play_quality(
    SseDeserializer deserializer,
  );

  @protected
  SliveRoomDetail sse_decode_box_autoadd_slive_room_detail(
    SseDeserializer deserializer,
  );

  @protected
  SliveSubCategory sse_decode_box_autoadd_slive_sub_category(
    SseDeserializer deserializer,
  );

  @protected
  SliveSuperChatMessage sse_decode_box_autoadd_slive_super_chat_message(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SliveAnchorItem> sse_decode_list_slive_anchor_item(
    SseDeserializer deserializer,
  );

  @protected
  List<SliveCategory> sse_decode_list_slive_category(
    SseDeserializer deserializer,
  );

  @protected
  List<SliveMapEntry> sse_decode_list_slive_map_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<SlivePlayQuality> sse_decode_list_slive_play_quality(
    SseDeserializer deserializer,
  );

  @protected
  List<SliveRoomItem> sse_decode_list_slive_room_item(
    SseDeserializer deserializer,
  );

  @protected
  List<SliveSubCategory> sse_decode_list_slive_sub_category(
    SseDeserializer deserializer,
  );

  @protected
  List<SliveSuperChatMessage> sse_decode_list_slive_super_chat_message(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  SliveDanmuItem? sse_decode_opt_box_autoadd_slive_danmu_item(
    SseDeserializer deserializer,
  );

  @protected
  List<SliveMapEntry>? sse_decode_opt_list_slive_map_entry(
    SseDeserializer deserializer,
  );

  @protected
  SliveAnchorItem sse_decode_slive_anchor_item(SseDeserializer deserializer);

  @protected
  SliveCategory sse_decode_slive_category(SseDeserializer deserializer);

  @protected
  SliveCategoryResult sse_decode_slive_category_result(
    SseDeserializer deserializer,
  );

  @protected
  SliveDanmuControlEvent sse_decode_slive_danmu_control_event(
    SseDeserializer deserializer,
  );

  @protected
  SliveDanmuItem sse_decode_slive_danmu_item(SseDeserializer deserializer);

  @protected
  SliveMapEntry sse_decode_slive_map_entry(SseDeserializer deserializer);

  @protected
  SliveMessage sse_decode_slive_message(SseDeserializer deserializer);

  @protected
  SliveMessageColor sse_decode_slive_message_color(
    SseDeserializer deserializer,
  );

  @protected
  SliveMessageType sse_decode_slive_message_type(SseDeserializer deserializer);

  @protected
  SlivePlayQuality sse_decode_slive_play_quality(SseDeserializer deserializer);

  @protected
  SlivePlayUrl sse_decode_slive_play_url(SseDeserializer deserializer);

  @protected
  SliveRoomDetail sse_decode_slive_room_detail(SseDeserializer deserializer);

  @protected
  SliveRoomItem sse_decode_slive_room_item(SseDeserializer deserializer);

  @protected
  SliveSearchAnchorResult sse_decode_slive_search_anchor_result(
    SseDeserializer deserializer,
  );

  @protected
  SliveSearchRoomResult sse_decode_slive_search_room_result(
    SseDeserializer deserializer,
  );

  @protected
  SliveSubCategory sse_decode_slive_sub_category(SseDeserializer deserializer);

  @protected
  SliveSuperChatMessage sse_decode_slive_super_chat_message(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliDanmakuProvider(
    SliveBilibiliDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliExtractor(
    SliveBilibiliExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDanmuConnection(
    SliveDanmuConnection self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinDanmakuProvider(
    SliveDouyinDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinExtractor(
    SliveDouyinExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuDanmakuProvider(
    SliveDouyuDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuExtractor(
    SliveDouyuExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaDanmakuProvider(
    SliveHuyaDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaExtractor(
    SliveHuyaExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchDanmakuProvider(
    SliveTwitchDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchExtractor(
    SliveTwitchExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDanmuConnection(
    SliveDanmuConnection self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliDanmakuProvider(
    SliveBilibiliDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliExtractor(
    SliveBilibiliExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDanmuConnection(
    SliveDanmuConnection self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinDanmakuProvider(
    SliveDouyinDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinExtractor(
    SliveDouyinExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuDanmakuProvider(
    SliveDouyuDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuExtractor(
    SliveDouyuExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaDanmakuProvider(
    SliveHuyaDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaExtractor(
    SliveHuyaExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchDanmakuProvider(
    SliveTwitchDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchExtractor(
    SliveTwitchExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliDanmakuProvider(
    SliveBilibiliDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliExtractor(
    SliveBilibiliExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDanmuConnection(
    SliveDanmuConnection self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinDanmakuProvider(
    SliveDouyinDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinExtractor(
    SliveDouyinExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuDanmakuProvider(
    SliveDouyuDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuExtractor(
    SliveDouyuExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaDanmakuProvider(
    SliveHuyaDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaExtractor(
    SliveHuyaExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchDanmakuProvider(
    SliveTwitchDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchExtractor(
    SliveTwitchExtractor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_slive_danmu_control_event(
    SliveDanmuControlEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_slive_danmu_item(
    SliveDanmuItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_slive_message(
    SliveMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_slive_play_quality(
    SlivePlayQuality self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_slive_room_detail(
    SliveRoomDetail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_slive_sub_category(
    SliveSubCategory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_slive_super_chat_message(
    SliveSuperChatMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_slive_anchor_item(
    List<SliveAnchorItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_slive_category(
    List<SliveCategory> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_slive_map_entry(
    List<SliveMapEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_slive_play_quality(
    List<SlivePlayQuality> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_slive_room_item(
    List<SliveRoomItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_slive_sub_category(
    List<SliveSubCategory> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_slive_super_chat_message(
    List<SliveSuperChatMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_slive_danmu_item(
    SliveDanmuItem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_slive_map_entry(
    List<SliveMapEntry>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_slive_anchor_item(
    SliveAnchorItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_slive_category(SliveCategory self, SseSerializer serializer);

  @protected
  void sse_encode_slive_category_result(
    SliveCategoryResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_slive_danmu_control_event(
    SliveDanmuControlEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_slive_danmu_item(
    SliveDanmuItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_slive_map_entry(SliveMapEntry self, SseSerializer serializer);

  @protected
  void sse_encode_slive_message(SliveMessage self, SseSerializer serializer);

  @protected
  void sse_encode_slive_message_color(
    SliveMessageColor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_slive_message_type(
    SliveMessageType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_slive_play_quality(
    SlivePlayQuality self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_slive_play_url(SlivePlayUrl self, SseSerializer serializer);

  @protected
  void sse_encode_slive_room_detail(
    SliveRoomDetail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_slive_room_item(SliveRoomItem self, SseSerializer serializer);

  @protected
  void sse_encode_slive_search_anchor_result(
    SliveSearchAnchorResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_slive_search_room_result(
    SliveSearchRoomResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_slive_sub_category(
    SliveSubCategory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_slive_super_chat_message(
    SliveSuperChatMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliDanmakuProvider(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliDanmakuProvider(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliDanmakuProvider(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliDanmakuProvider(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliExtractor(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliExtractor(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliExtractor(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliExtractor(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDanmuConnection(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDanmuConnection(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDanmuConnection(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDanmuConnection(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinDanmakuProvider(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinDanmakuProvider(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinDanmakuProvider(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinDanmakuProvider(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinExtractor(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinExtractor(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinExtractor(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinExtractor(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuDanmakuProvider(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuDanmakuProvider(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuDanmakuProvider(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuDanmakuProvider(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuExtractor(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuExtractor(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuExtractor(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuExtractor(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaDanmakuProvider(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaDanmakuProvider(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaDanmakuProvider(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaDanmakuProvider(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaExtractor(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaExtractor(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaExtractor(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaExtractor(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchDanmakuProvider(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchDanmakuProvider(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchDanmakuProvider(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchDanmakuProvider(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchExtractor(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchExtractor(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchExtractor(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchExtractor(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliDanmakuProvider(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliDanmakuProvider(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliExtractor(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveBilibiliExtractor(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDanmuConnection(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDanmuConnection(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinDanmakuProvider(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinDanmakuProvider(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinExtractor(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyinExtractor(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuDanmakuProvider(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuDanmakuProvider(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuExtractor(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveDouyuExtractor(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaDanmakuProvider(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaDanmakuProvider(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaExtractor(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveHuyaExtractor(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchDanmakuProvider(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchDanmakuProvider(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchExtractor(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSliveTwitchExtractor(
    int ptr,
  );
}
