// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/danmaku.dart';
import 'api/extractor.dart';
import 'api/log.dart';
import 'api/models/live_anchor_item.dart';
import 'api/models/live_category.dart';
import 'api/models/live_category_result.dart';
import 'api/models/live_danmu_control_event.dart';
import 'api/models/live_danmu_item.dart';
import 'api/models/live_mask_config.dart';
import 'api/models/live_mask_stats.dart';
import 'api/models/live_message.dart';
import 'api/models/live_message_color.dart';
import 'api/models/live_message_type.dart';
import 'api/models/live_play_quality.dart';
import 'api/models/live_play_url.dart';
import 'api/models/live_room_detail.dart';
import 'api/models/live_room_item.dart';
import 'api/models/live_search_anchor_result.dart';
import 'api/models/live_search_room_result.dart';
import 'api/models/live_sub_category.dart';
import 'api/models/live_super_chat_message.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LiveBilibiliDanmakuProviderPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliDanmakuProviderPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LiveBilibiliExtractorPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliExtractorPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LiveDanmuConnectionPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnectionPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LiveDouyinDanmakuProviderPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinDanmakuProviderPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LiveDouyinExtractorPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinExtractorPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LiveDouyuDanmakuProviderPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuDanmakuProviderPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LiveDouyuExtractorPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuExtractorPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LiveHuyaDanmakuProviderPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaDanmakuProviderPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LiveHuyaExtractorPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaExtractorPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LiveTwitchDanmakuProviderPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchDanmakuProviderPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LiveTwitchExtractorPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchExtractorPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  LiveBilibiliDanmakuProvider
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliDanmakuProvider(
    dynamic raw,
  );

  @protected
  LiveBilibiliExtractor
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliExtractor(
    dynamic raw,
  );

  @protected
  LiveDanmuConnection
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnection(
    dynamic raw,
  );

  @protected
  LiveDouyinDanmakuProvider
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinDanmakuProvider(
    dynamic raw,
  );

  @protected
  LiveDouyinExtractor
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinExtractor(
    dynamic raw,
  );

  @protected
  LiveDouyuDanmakuProvider
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuDanmakuProvider(
    dynamic raw,
  );

  @protected
  LiveDouyuExtractor
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuExtractor(
    dynamic raw,
  );

  @protected
  LiveHuyaDanmakuProvider
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaDanmakuProvider(
    dynamic raw,
  );

  @protected
  LiveHuyaExtractor
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaExtractor(
    dynamic raw,
  );

  @protected
  LiveTwitchDanmakuProvider
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchDanmakuProvider(
    dynamic raw,
  );

  @protected
  LiveTwitchExtractor
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchExtractor(
    dynamic raw,
  );

  @protected
  LiveDanmuConnection
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnection(
    dynamic raw,
  );

  @protected
  LiveBilibiliDanmakuProvider
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliDanmakuProvider(
    dynamic raw,
  );

  @protected
  LiveBilibiliExtractor
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliExtractor(
    dynamic raw,
  );

  @protected
  LiveDanmuConnection
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnection(
    dynamic raw,
  );

  @protected
  LiveDouyinDanmakuProvider
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinDanmakuProvider(
    dynamic raw,
  );

  @protected
  LiveDouyinExtractor
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinExtractor(
    dynamic raw,
  );

  @protected
  LiveDouyuDanmakuProvider
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuDanmakuProvider(
    dynamic raw,
  );

  @protected
  LiveDouyuExtractor
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuExtractor(
    dynamic raw,
  );

  @protected
  LiveHuyaDanmakuProvider
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaDanmakuProvider(
    dynamic raw,
  );

  @protected
  LiveHuyaExtractor
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaExtractor(
    dynamic raw,
  );

  @protected
  LiveTwitchDanmakuProvider
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchDanmakuProvider(
    dynamic raw,
  );

  @protected
  LiveTwitchExtractor
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchExtractor(
    dynamic raw,
  );

  @protected
  int dco_decode_CastedPrimitive_i_64(dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  LiveBilibiliDanmakuProvider
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliDanmakuProvider(
    dynamic raw,
  );

  @protected
  LiveBilibiliExtractor
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliExtractor(
    dynamic raw,
  );

  @protected
  LiveDanmuConnection
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnection(
    dynamic raw,
  );

  @protected
  LiveDouyinDanmakuProvider
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinDanmakuProvider(
    dynamic raw,
  );

  @protected
  LiveDouyinExtractor
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinExtractor(
    dynamic raw,
  );

  @protected
  LiveDouyuDanmakuProvider
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuDanmakuProvider(
    dynamic raw,
  );

  @protected
  LiveDouyuExtractor
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuExtractor(
    dynamic raw,
  );

  @protected
  LiveHuyaDanmakuProvider
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaDanmakuProvider(
    dynamic raw,
  );

  @protected
  LiveHuyaExtractor
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaExtractor(
    dynamic raw,
  );

  @protected
  LiveTwitchDanmakuProvider
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchDanmakuProvider(
    dynamic raw,
  );

  @protected
  LiveTwitchExtractor
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchExtractor(
    dynamic raw,
  );

  @protected
  RustStreamSink<LogEntry> dco_decode_StreamSink_log_entry_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  LiveDanmuControlEvent dco_decode_box_autoadd_live_danmu_control_event(
    dynamic raw,
  );

  @protected
  LiveDanmuItem dco_decode_box_autoadd_live_danmu_item(dynamic raw);

  @protected
  LiveFrequencyConfig dco_decode_box_autoadd_live_frequency_config(dynamic raw);

  @protected
  LiveMaskConfig dco_decode_box_autoadd_live_mask_config(dynamic raw);

  @protected
  LiveMessage dco_decode_box_autoadd_live_message(dynamic raw);

  @protected
  LiveMessageColor dco_decode_box_autoadd_live_message_color(dynamic raw);

  @protected
  LivePlayQuality dco_decode_box_autoadd_live_play_quality(dynamic raw);

  @protected
  LiveRoomDetail dco_decode_box_autoadd_live_room_detail(dynamic raw);

  @protected
  LiveSubCategory dco_decode_box_autoadd_live_sub_category(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Level dco_decode_level(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<LiveAnchorItem> dco_decode_list_live_anchor_item(dynamic raw);

  @protected
  List<LiveCategory> dco_decode_list_live_category(dynamic raw);

  @protected
  List<LivePlayQuality> dco_decode_list_live_play_quality(dynamic raw);

  @protected
  List<LiveRoomItem> dco_decode_list_live_room_item(dynamic raw);

  @protected
  List<LiveSubCategory> dco_decode_list_live_sub_category(dynamic raw);

  @protected
  List<LiveSuperChatMessage> dco_decode_list_live_super_chat_message(
    dynamic raw,
  );

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  LiveAnchorItem dco_decode_live_anchor_item(dynamic raw);

  @protected
  LiveCategory dco_decode_live_category(dynamic raw);

  @protected
  LiveCategoryResult dco_decode_live_category_result(dynamic raw);

  @protected
  LiveDanmuControlEvent dco_decode_live_danmu_control_event(dynamic raw);

  @protected
  LiveDanmuItem dco_decode_live_danmu_item(dynamic raw);

  @protected
  LiveFrequencyConfig dco_decode_live_frequency_config(dynamic raw);

  @protected
  LiveMaskConfig dco_decode_live_mask_config(dynamic raw);

  @protected
  LiveMaskStats dco_decode_live_mask_stats(dynamic raw);

  @protected
  LiveMessage dco_decode_live_message(dynamic raw);

  @protected
  LiveMessageColor dco_decode_live_message_color(dynamic raw);

  @protected
  LiveMessageType dco_decode_live_message_type(dynamic raw);

  @protected
  LivePlayQuality dco_decode_live_play_quality(dynamic raw);

  @protected
  LivePlayUrl dco_decode_live_play_url(dynamic raw);

  @protected
  LiveRoomDetail dco_decode_live_room_detail(dynamic raw);

  @protected
  LiveRoomItem dco_decode_live_room_item(dynamic raw);

  @protected
  LiveSearchAnchorResult dco_decode_live_search_anchor_result(dynamic raw);

  @protected
  LiveSearchRoomResult dco_decode_live_search_room_result(dynamic raw);

  @protected
  LiveSubCategory dco_decode_live_sub_category(dynamic raw);

  @protected
  LiveSuperChatMessage dco_decode_live_super_chat_message(dynamic raw);

  @protected
  LogEntry dco_decode_log_entry(dynamic raw);

  @protected
  Map<String, String>? dco_decode_opt_Map_String_String_None(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  LiveDanmuItem? dco_decode_opt_box_autoadd_live_danmu_item(dynamic raw);

  @protected
  LiveFrequencyConfig? dco_decode_opt_box_autoadd_live_frequency_config(
    dynamic raw,
  );

  @protected
  LiveMaskConfig? dco_decode_opt_box_autoadd_live_mask_config(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  LiveBilibiliDanmakuProvider
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  LiveBilibiliExtractor
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliExtractor(
    SseDeserializer deserializer,
  );

  @protected
  LiveDanmuConnection
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnection(
    SseDeserializer deserializer,
  );

  @protected
  LiveDouyinDanmakuProvider
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  LiveDouyinExtractor
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinExtractor(
    SseDeserializer deserializer,
  );

  @protected
  LiveDouyuDanmakuProvider
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  LiveDouyuExtractor
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuExtractor(
    SseDeserializer deserializer,
  );

  @protected
  LiveHuyaDanmakuProvider
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  LiveHuyaExtractor
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaExtractor(
    SseDeserializer deserializer,
  );

  @protected
  LiveTwitchDanmakuProvider
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  LiveTwitchExtractor
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchExtractor(
    SseDeserializer deserializer,
  );

  @protected
  LiveDanmuConnection
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnection(
    SseDeserializer deserializer,
  );

  @protected
  LiveBilibiliDanmakuProvider
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  LiveBilibiliExtractor
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliExtractor(
    SseDeserializer deserializer,
  );

  @protected
  LiveDanmuConnection
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnection(
    SseDeserializer deserializer,
  );

  @protected
  LiveDouyinDanmakuProvider
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  LiveDouyinExtractor
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinExtractor(
    SseDeserializer deserializer,
  );

  @protected
  LiveDouyuDanmakuProvider
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  LiveDouyuExtractor
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuExtractor(
    SseDeserializer deserializer,
  );

  @protected
  LiveHuyaDanmakuProvider
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  LiveHuyaExtractor
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaExtractor(
    SseDeserializer deserializer,
  );

  @protected
  LiveTwitchDanmakuProvider
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  LiveTwitchExtractor
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchExtractor(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_CastedPrimitive_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  LiveBilibiliDanmakuProvider
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  LiveBilibiliExtractor
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliExtractor(
    SseDeserializer deserializer,
  );

  @protected
  LiveDanmuConnection
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnection(
    SseDeserializer deserializer,
  );

  @protected
  LiveDouyinDanmakuProvider
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  LiveDouyinExtractor
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinExtractor(
    SseDeserializer deserializer,
  );

  @protected
  LiveDouyuDanmakuProvider
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  LiveDouyuExtractor
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuExtractor(
    SseDeserializer deserializer,
  );

  @protected
  LiveHuyaDanmakuProvider
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  LiveHuyaExtractor
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaExtractor(
    SseDeserializer deserializer,
  );

  @protected
  LiveTwitchDanmakuProvider
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchDanmakuProvider(
    SseDeserializer deserializer,
  );

  @protected
  LiveTwitchExtractor
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchExtractor(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<LogEntry> sse_decode_StreamSink_log_entry_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  LiveDanmuControlEvent sse_decode_box_autoadd_live_danmu_control_event(
    SseDeserializer deserializer,
  );

  @protected
  LiveDanmuItem sse_decode_box_autoadd_live_danmu_item(
    SseDeserializer deserializer,
  );

  @protected
  LiveFrequencyConfig sse_decode_box_autoadd_live_frequency_config(
    SseDeserializer deserializer,
  );

  @protected
  LiveMaskConfig sse_decode_box_autoadd_live_mask_config(
    SseDeserializer deserializer,
  );

  @protected
  LiveMessage sse_decode_box_autoadd_live_message(SseDeserializer deserializer);

  @protected
  LiveMessageColor sse_decode_box_autoadd_live_message_color(
    SseDeserializer deserializer,
  );

  @protected
  LivePlayQuality sse_decode_box_autoadd_live_play_quality(
    SseDeserializer deserializer,
  );

  @protected
  LiveRoomDetail sse_decode_box_autoadd_live_room_detail(
    SseDeserializer deserializer,
  );

  @protected
  LiveSubCategory sse_decode_box_autoadd_live_sub_category(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Level sse_decode_level(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<LiveAnchorItem> sse_decode_list_live_anchor_item(
    SseDeserializer deserializer,
  );

  @protected
  List<LiveCategory> sse_decode_list_live_category(
    SseDeserializer deserializer,
  );

  @protected
  List<LivePlayQuality> sse_decode_list_live_play_quality(
    SseDeserializer deserializer,
  );

  @protected
  List<LiveRoomItem> sse_decode_list_live_room_item(
    SseDeserializer deserializer,
  );

  @protected
  List<LiveSubCategory> sse_decode_list_live_sub_category(
    SseDeserializer deserializer,
  );

  @protected
  List<LiveSuperChatMessage> sse_decode_list_live_super_chat_message(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  LiveAnchorItem sse_decode_live_anchor_item(SseDeserializer deserializer);

  @protected
  LiveCategory sse_decode_live_category(SseDeserializer deserializer);

  @protected
  LiveCategoryResult sse_decode_live_category_result(
    SseDeserializer deserializer,
  );

  @protected
  LiveDanmuControlEvent sse_decode_live_danmu_control_event(
    SseDeserializer deserializer,
  );

  @protected
  LiveDanmuItem sse_decode_live_danmu_item(SseDeserializer deserializer);

  @protected
  LiveFrequencyConfig sse_decode_live_frequency_config(
    SseDeserializer deserializer,
  );

  @protected
  LiveMaskConfig sse_decode_live_mask_config(SseDeserializer deserializer);

  @protected
  LiveMaskStats sse_decode_live_mask_stats(SseDeserializer deserializer);

  @protected
  LiveMessage sse_decode_live_message(SseDeserializer deserializer);

  @protected
  LiveMessageColor sse_decode_live_message_color(SseDeserializer deserializer);

  @protected
  LiveMessageType sse_decode_live_message_type(SseDeserializer deserializer);

  @protected
  LivePlayQuality sse_decode_live_play_quality(SseDeserializer deserializer);

  @protected
  LivePlayUrl sse_decode_live_play_url(SseDeserializer deserializer);

  @protected
  LiveRoomDetail sse_decode_live_room_detail(SseDeserializer deserializer);

  @protected
  LiveRoomItem sse_decode_live_room_item(SseDeserializer deserializer);

  @protected
  LiveSearchAnchorResult sse_decode_live_search_anchor_result(
    SseDeserializer deserializer,
  );

  @protected
  LiveSearchRoomResult sse_decode_live_search_room_result(
    SseDeserializer deserializer,
  );

  @protected
  LiveSubCategory sse_decode_live_sub_category(SseDeserializer deserializer);

  @protected
  LiveSuperChatMessage sse_decode_live_super_chat_message(
    SseDeserializer deserializer,
  );

  @protected
  LogEntry sse_decode_log_entry(SseDeserializer deserializer);

  @protected
  Map<String, String>? sse_decode_opt_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  LiveDanmuItem? sse_decode_opt_box_autoadd_live_danmu_item(
    SseDeserializer deserializer,
  );

  @protected
  LiveFrequencyConfig? sse_decode_opt_box_autoadd_live_frequency_config(
    SseDeserializer deserializer,
  );

  @protected
  LiveMaskConfig? sse_decode_opt_box_autoadd_live_mask_config(
    SseDeserializer deserializer,
  );

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliDanmakuProvider(
    LiveBilibiliDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliExtractor(
    LiveBilibiliExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnection(
    LiveDanmuConnection self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinDanmakuProvider(
    LiveDouyinDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinExtractor(
    LiveDouyinExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuDanmakuProvider(
    LiveDouyuDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuExtractor(
    LiveDouyuExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaDanmakuProvider(
    LiveHuyaDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaExtractor(
    LiveHuyaExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchDanmakuProvider(
    LiveTwitchDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchExtractor(
    LiveTwitchExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnection(
    LiveDanmuConnection self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliDanmakuProvider(
    LiveBilibiliDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliExtractor(
    LiveBilibiliExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnection(
    LiveDanmuConnection self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinDanmakuProvider(
    LiveDouyinDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinExtractor(
    LiveDouyinExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuDanmakuProvider(
    LiveDouyuDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuExtractor(
    LiveDouyuExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaDanmakuProvider(
    LiveHuyaDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaExtractor(
    LiveHuyaExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchDanmakuProvider(
    LiveTwitchDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchExtractor(
    LiveTwitchExtractor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_CastedPrimitive_i_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliDanmakuProvider(
    LiveBilibiliDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliExtractor(
    LiveBilibiliExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnection(
    LiveDanmuConnection self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinDanmakuProvider(
    LiveDouyinDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinExtractor(
    LiveDouyinExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuDanmakuProvider(
    LiveDouyuDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuExtractor(
    LiveDouyuExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaDanmakuProvider(
    LiveHuyaDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaExtractor(
    LiveHuyaExtractor self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchDanmakuProvider(
    LiveTwitchDanmakuProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchExtractor(
    LiveTwitchExtractor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_log_entry_Sse(
    RustStreamSink<LogEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_live_danmu_control_event(
    LiveDanmuControlEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_live_danmu_item(
    LiveDanmuItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_live_frequency_config(
    LiveFrequencyConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_live_mask_config(
    LiveMaskConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_live_message(
    LiveMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_live_message_color(
    LiveMessageColor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_live_play_quality(
    LivePlayQuality self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_live_room_detail(
    LiveRoomDetail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_live_sub_category(
    LiveSubCategory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_level(Level self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_live_anchor_item(
    List<LiveAnchorItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_live_category(
    List<LiveCategory> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_live_play_quality(
    List<LivePlayQuality> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_live_room_item(
    List<LiveRoomItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_live_sub_category(
    List<LiveSubCategory> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_live_super_chat_message(
    List<LiveSuperChatMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_live_anchor_item(
    LiveAnchorItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_live_category(LiveCategory self, SseSerializer serializer);

  @protected
  void sse_encode_live_category_result(
    LiveCategoryResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_live_danmu_control_event(
    LiveDanmuControlEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_live_danmu_item(LiveDanmuItem self, SseSerializer serializer);

  @protected
  void sse_encode_live_frequency_config(
    LiveFrequencyConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_live_mask_config(
    LiveMaskConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_live_mask_stats(LiveMaskStats self, SseSerializer serializer);

  @protected
  void sse_encode_live_message(LiveMessage self, SseSerializer serializer);

  @protected
  void sse_encode_live_message_color(
    LiveMessageColor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_live_message_type(
    LiveMessageType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_live_play_quality(
    LivePlayQuality self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_live_play_url(LivePlayUrl self, SseSerializer serializer);

  @protected
  void sse_encode_live_room_detail(
    LiveRoomDetail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_live_room_item(LiveRoomItem self, SseSerializer serializer);

  @protected
  void sse_encode_live_search_anchor_result(
    LiveSearchAnchorResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_live_search_room_result(
    LiveSearchRoomResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_live_sub_category(
    LiveSubCategory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_live_super_chat_message(
    LiveSuperChatMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_log_entry(LogEntry self, SseSerializer serializer);

  @protected
  void sse_encode_opt_Map_String_String_None(
    Map<String, String>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_live_danmu_item(
    LiveDanmuItem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_live_frequency_config(
    LiveFrequencyConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_live_mask_config(
    LiveMaskConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliDanmakuProvider(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliDanmakuProvider(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliDanmakuProviderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_slive_core_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliDanmakuProvider',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliDanmakuProvider =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliDanmakuProviderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliDanmakuProvider(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliDanmakuProvider(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliDanmakuProviderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_slive_core_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliDanmakuProvider',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliDanmakuProvider =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliDanmakuProviderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliExtractor(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliExtractor(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliExtractorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_slive_core_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliExtractor',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliExtractor =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliExtractorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliExtractor(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliExtractor(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliExtractorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_slive_core_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliExtractor',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliExtractor =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveBilibiliExtractorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnection(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnection(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnectionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_slive_core_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnection',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnection =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnectionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnection(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnection(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnectionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_slive_core_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnection',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnection =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDanmuConnectionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinDanmakuProvider(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinDanmakuProvider(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinDanmakuProviderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_slive_core_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinDanmakuProvider',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinDanmakuProvider =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinDanmakuProviderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinDanmakuProvider(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinDanmakuProvider(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinDanmakuProviderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_slive_core_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinDanmakuProvider',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinDanmakuProvider =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinDanmakuProviderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinExtractor(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinExtractor(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinExtractorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_slive_core_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinExtractor',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinExtractor =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinExtractorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinExtractor(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinExtractor(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinExtractorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_slive_core_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinExtractor',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinExtractor =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyinExtractorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuDanmakuProvider(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuDanmakuProvider(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuDanmakuProviderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_slive_core_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuDanmakuProvider',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuDanmakuProvider =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuDanmakuProviderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuDanmakuProvider(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuDanmakuProvider(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuDanmakuProviderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_slive_core_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuDanmakuProvider',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuDanmakuProvider =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuDanmakuProviderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuExtractor(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuExtractor(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuExtractorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_slive_core_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuExtractor',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuExtractor =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuExtractorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuExtractor(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuExtractor(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuExtractorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_slive_core_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuExtractor',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuExtractor =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveDouyuExtractorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaDanmakuProvider(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaDanmakuProvider(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaDanmakuProviderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_slive_core_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaDanmakuProvider',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaDanmakuProvider =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaDanmakuProviderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaDanmakuProvider(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaDanmakuProvider(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaDanmakuProviderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_slive_core_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaDanmakuProvider',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaDanmakuProvider =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaDanmakuProviderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaExtractor(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaExtractor(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaExtractorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_slive_core_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaExtractor',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaExtractor =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaExtractorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaExtractor(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaExtractor(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaExtractorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_slive_core_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaExtractor',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaExtractor =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveHuyaExtractorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchDanmakuProvider(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchDanmakuProvider(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchDanmakuProviderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_slive_core_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchDanmakuProvider',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchDanmakuProvider =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchDanmakuProviderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchDanmakuProvider(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchDanmakuProvider(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchDanmakuProviderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_slive_core_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchDanmakuProvider',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchDanmakuProvider =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchDanmakuProviderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchExtractor(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchExtractor(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchExtractorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_slive_core_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchExtractor',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchExtractor =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchExtractorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchExtractor(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchExtractor(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchExtractorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_slive_core_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchExtractor',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchExtractor =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLiveTwitchExtractorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
