// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// frb-compatible mirror of `MaskStats`.
class LiveMaskStats {
  /// Total messages received from the inner provider.
  final int totalReceived;

  /// Messages that passed the mask.
  final int passed;

  /// Messages blocked by the mask.
  final int blocked;

  const LiveMaskStats({
    required this.totalReceived,
    required this.passed,
    required this.blocked,
  });

  @override
  int get hashCode =>
      totalReceived.hashCode ^ passed.hashCode ^ blocked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveMaskStats &&
          runtimeType == other.runtimeType &&
          totalReceived == other.totalReceived &&
          passed == other.passed &&
          blocked == other.blocked;
}
