// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

class LivePlayUrl {
  final List<String> urls;
  final Map<String, String>? headers;

  const LivePlayUrl({required this.urls, this.headers});

  @override
  int get hashCode => urls.hashCode ^ headers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LivePlayUrl &&
          runtimeType == other.runtimeType &&
          urls == other.urls &&
          headers == other.headers;
}
