// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'live_super_chat_message.freezed.dart';
part 'live_super_chat_message.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`, `from`

@freezed
sealed class LiveSuperChatMessage with _$LiveSuperChatMessage {
  const factory LiveSuperChatMessage({
    required String userName,
    required String face,
    required String message,
    required int price,
    required int startTime,
    required int endTime,
    required String backgroundColor,
    required String backgroundBottomColor,
  }) = _LiveSuperChatMessage;

  factory LiveSuperChatMessage.fromJson(Map<String, dynamic> json) =>
      _$LiveSuperChatMessageFromJson(json);
}
