// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

class LiveAnchorItem {
  final String roomId;
  final String avatar;
  final String userName;
  final bool liveStatus;

  const LiveAnchorItem({
    required this.roomId,
    required this.avatar,
    required this.userName,
    required this.liveStatus,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      avatar.hashCode ^
      userName.hashCode ^
      liveStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveAnchorItem &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          avatar == other.avatar &&
          userName == other.userName &&
          liveStatus == other.liveStatus;
}
