// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'live_message_color.dart';
import 'live_message_type.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `danmu_type_to_message_type`, `parse_hex_color`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// Mirrors `DanmuMessage` from platforms-parser.
class LiveMessage {
  final String id;
  final String userId;
  final String userName;
  final String message;
  final LiveMessageColor color;

  /// Unix timestamp in milliseconds.
  final int timeMillis;
  final LiveMessageType messageType;

  /// Platform-specific metadata serialized as JSON string.
  final String? metadata;

  const LiveMessage({
    required this.id,
    required this.userId,
    required this.userName,
    required this.message,
    required this.color,
    required this.timeMillis,
    required this.messageType,
    this.metadata,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      userId.hashCode ^
      userName.hashCode ^
      message.hashCode ^
      color.hashCode ^
      timeMillis.hashCode ^
      messageType.hashCode ^
      metadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          userId == other.userId &&
          userName == other.userName &&
          message == other.message &&
          color == other.color &&
          timeMillis == other.timeMillis &&
          messageType == other.messageType &&
          metadata == other.metadata;
}
