// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`, `from`

class LiveRoomDetail {
  final String roomId;
  final String title;
  final String cover;
  final String userName;
  final String userAvatar;
  final int online;
  final String? introduction;
  final String? notice;
  final bool status;

  /// Platform-specific data serialized as JSON string.
  final String? data;

  /// Danmaku connection data serialized as JSON string.
  final String? danmakuData;
  final String url;
  final bool isRecord;

  const LiveRoomDetail({
    required this.roomId,
    required this.title,
    required this.cover,
    required this.userName,
    required this.userAvatar,
    required this.online,
    this.introduction,
    this.notice,
    required this.status,
    this.data,
    this.danmakuData,
    required this.url,
    required this.isRecord,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      title.hashCode ^
      cover.hashCode ^
      userName.hashCode ^
      userAvatar.hashCode ^
      online.hashCode ^
      introduction.hashCode ^
      notice.hashCode ^
      status.hashCode ^
      data.hashCode ^
      danmakuData.hashCode ^
      url.hashCode ^
      isRecord.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveRoomDetail &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          title == other.title &&
          cover == other.cover &&
          userName == other.userName &&
          userAvatar == other.userAvatar &&
          online == other.online &&
          introduction == other.introduction &&
          notice == other.notice &&
          status == other.status &&
          data == other.data &&
          danmakuData == other.danmakuData &&
          url == other.url &&
          isRecord == other.isRecord;
}
