// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Mirrors `LiveMessageColor` from the reference.
class LiveMessageColor {
  final int r;
  final int g;
  final int b;

  const LiveMessageColor({required this.r, required this.g, required this.b});

  static LiveMessageColor fromInt({required int intColor}) => RustLib
      .instance
      .api
      .crateApiModelsLiveMessageColorLiveMessageColorFromInt(
        intColor: intColor,
      );

  String toHex() => RustLib.instance.api
      .crateApiModelsLiveMessageColorLiveMessageColorToHex(that: this);

  static LiveMessageColor white() => RustLib.instance.api
      .crateApiModelsLiveMessageColorLiveMessageColorWhite();

  @override
  int get hashCode => r.hashCode ^ g.hashCode ^ b.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveMessageColor &&
          runtimeType == other.runtimeType &&
          r == other.r &&
          g == other.g &&
          b == other.b;
}
