// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// Mirrors `LiveMessage` superChat variant — kept as a separate type because
/// frb does not support `dynamic` fields, so the super-chat payload is typed.
class LiveDanmuControlEvent {
  final String kind;
  final String? message;
  final String? title;
  final String? category;
  final String? parentCategory;

  const LiveDanmuControlEvent({
    required this.kind,
    this.message,
    this.title,
    this.category,
    this.parentCategory,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      message.hashCode ^
      title.hashCode ^
      category.hashCode ^
      parentCategory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveDanmuControlEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message &&
          title == other.title &&
          category == other.category &&
          parentCategory == other.parentCategory;
}
