// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`, `from`

class LiveSubCategory {
  final String id;
  final String name;
  final String parentId;
  final String? pic;

  const LiveSubCategory({
    required this.id,
    required this.name,
    required this.parentId,
    this.pic,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ parentId.hashCode ^ pic.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveSubCategory &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          parentId == other.parentId &&
          pic == other.pic;
}
