// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`, `from`

/// frb-compatible mirror of `FrequencyConfig`.
class LiveFrequencyConfig {
  final int baseWindowMs;
  final int bucketCount;
  final bool useNormalization;
  final int maxFrequency;

  const LiveFrequencyConfig({
    required this.baseWindowMs,
    required this.bucketCount,
    required this.useNormalization,
    required this.maxFrequency,
  });

  @override
  int get hashCode =>
      baseWindowMs.hashCode ^
      bucketCount.hashCode ^
      useNormalization.hashCode ^
      maxFrequency.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveFrequencyConfig &&
          runtimeType == other.runtimeType &&
          baseWindowMs == other.baseWindowMs &&
          bucketCount == other.bucketCount &&
          useNormalization == other.useNormalization &&
          maxFrequency == other.maxFrequency;
}

/// frb-compatible mirror of `MaskConfig`.
class LiveMaskConfig {
  final LiveFrequencyConfig? frequency;
  final List<String>? blacklistWords;

  const LiveMaskConfig({this.frequency, this.blacklistWords});

  @override
  int get hashCode => frequency.hashCode ^ blacklistWords.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveMaskConfig &&
          runtimeType == other.runtimeType &&
          frequency == other.frequency &&
          blacklistWords == other.blacklistWords;
}
