// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'live_danmu_control_event.dart';
import 'live_message.dart';
import 'live_message_color.dart';
import 'live_message_type.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'live_danmu_item.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

@freezed
sealed class LiveDanmuItem with _$LiveDanmuItem {
  const LiveDanmuItem._();

  const factory LiveDanmuItem.message(LiveMessage field0) =
      LiveDanmuItem_Message;
  const factory LiveDanmuItem.control(LiveDanmuControlEvent field0) =
      LiveDanmuItem_Control;
}
