// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Diagnostic: test Douyu danmaku connection end-to-end from the Rust side.
/// Returns a log of what happened during the test.
Future<String> douyuDanmakuDiagnostic({required String roomId}) =>
    RustLib.instance.api.crateApiDanmakuDouyuDanmakuDiagnostic(roomId: roomId);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SliveBilibiliDanmakuProvider>>
abstract class SliveBilibiliDanmakuProvider implements RustOpaqueInterface {
  Future<SliveDanmuConnection> connect({
    required String roomId,
    String? cookies,
  });

  Future<void> disconnect({required SliveDanmuConnection connection});

  Future<String?> extractRoomId({required String url});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SliveBilibiliDanmakuProvider> newInstance() =>
      RustLib.instance.api.crateApiDanmakuSliveBilibiliDanmakuProviderNew();

  Future<SliveDanmuItem?> receive({required SliveDanmuConnection connection});

  Future<bool> supportsUrl({required String url});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SliveDanmuConnection>>
abstract class SliveDanmuConnection implements RustOpaqueInterface {
  Future<bool> isConnected();

  Future<String> platform();

  Future<String> roomId();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SliveDouyinDanmakuProvider>>
abstract class SliveDouyinDanmakuProvider implements RustOpaqueInterface {
  Future<SliveDanmuConnection> connect({
    required String roomId,
    String? cookies,
  });

  Future<void> disconnect({required SliveDanmuConnection connection});

  Future<String?> extractRoomId({required String url});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SliveDouyinDanmakuProvider> newInstance() =>
      RustLib.instance.api.crateApiDanmakuSliveDouyinDanmakuProviderNew();

  Future<SliveDanmuItem?> receive({required SliveDanmuConnection connection});

  Future<bool> supportsUrl({required String url});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SliveDouyuDanmakuProvider>>
abstract class SliveDouyuDanmakuProvider implements RustOpaqueInterface {
  Future<SliveDanmuConnection> connect({
    required String roomId,
    String? cookies,
  });

  Future<void> disconnect({required SliveDanmuConnection connection});

  Future<String?> extractRoomId({required String url});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SliveDouyuDanmakuProvider> newInstance() =>
      RustLib.instance.api.crateApiDanmakuSliveDouyuDanmakuProviderNew();

  Future<SliveDanmuItem?> receive({required SliveDanmuConnection connection});

  Future<bool> supportsUrl({required String url});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SliveHuyaDanmakuProvider>>
abstract class SliveHuyaDanmakuProvider implements RustOpaqueInterface {
  Future<SliveDanmuConnection> connect({
    required String roomId,
    String? cookies,
  });

  /// Connect to Huya danmaku with extra parameters (ayyuid, top_sid, sub_sid).
  Future<SliveDanmuConnection> connectWithExtras({
    required String roomId,
    String? cookies,
    required PlatformInt64 ayyuid,
    required PlatformInt64 topSid,
    required PlatformInt64 subSid,
  });

  Future<void> disconnect({required SliveDanmuConnection connection});

  Future<String?> extractRoomId({required String url});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SliveHuyaDanmakuProvider> newInstance() =>
      RustLib.instance.api.crateApiDanmakuSliveHuyaDanmakuProviderNew();

  Future<SliveDanmuItem?> receive({required SliveDanmuConnection connection});

  Future<bool> supportsUrl({required String url});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SliveTwitchDanmakuProvider>>
abstract class SliveTwitchDanmakuProvider implements RustOpaqueInterface {
  Future<SliveDanmuConnection> connect({
    required String roomId,
    String? cookies,
  });

  Future<void> disconnect({required SliveDanmuConnection connection});

  Future<String?> extractRoomId({required String url});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SliveTwitchDanmakuProvider> newInstance() =>
      RustLib.instance.api.crateApiDanmakuSliveTwitchDanmakuProviderNew();

  Future<SliveDanmuItem?> receive({required SliveDanmuConnection connection});

  Future<bool> supportsUrl({required String url});
}
