// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Diagnostic: test Douyu danmaku connection end-to-end from the Rust side.
/// Returns a log of what happened during the test.
Future<String> douyuDanmakuDiagnostic({required String roomId}) =>
    RustLib.instance.api.crateApiDanmakuDouyuDanmakuDiagnostic(roomId: roomId);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LiveBilibiliDanmakuProvider>>
abstract class LiveBilibiliDanmakuProvider implements RustOpaqueInterface {
  Future<LiveDanmuConnection> connect({
    required String roomId,
    String? cookies,
    String? danmakuData,
  });

  Future<void> disconnect({required LiveDanmuConnection connection});

  Future<String?> extractRoomId({required String url});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<LiveBilibiliDanmakuProvider> newInstance() =>
      RustLib.instance.api.crateApiDanmakuLiveBilibiliDanmakuProviderNew();

  Future<LiveDanmuItem?> receive({required LiveDanmuConnection connection});

  Future<bool> supportsUrl({required String url});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LiveDanmuConnection>>
abstract class LiveDanmuConnection implements RustOpaqueInterface {
  Future<bool> isConnected();

  Future<String> platform();

  Future<String> roomId();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LiveDouyinDanmakuProvider>>
abstract class LiveDouyinDanmakuProvider implements RustOpaqueInterface {
  Future<LiveDanmuConnection> connect({
    required String roomId,
    String? cookies,
    String? danmakuData,
  });

  Future<void> disconnect({required LiveDanmuConnection connection});

  Future<String?> extractRoomId({required String url});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<LiveDouyinDanmakuProvider> newInstance() =>
      RustLib.instance.api.crateApiDanmakuLiveDouyinDanmakuProviderNew();

  Future<LiveDanmuItem?> receive({required LiveDanmuConnection connection});

  Future<bool> supportsUrl({required String url});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LiveDouyuDanmakuProvider>>
abstract class LiveDouyuDanmakuProvider implements RustOpaqueInterface {
  Future<LiveDanmuConnection> connect({
    required String roomId,
    String? cookies,
    String? danmakuData,
  });

  Future<void> disconnect({required LiveDanmuConnection connection});

  Future<String?> extractRoomId({required String url});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<LiveDouyuDanmakuProvider> newInstance() =>
      RustLib.instance.api.crateApiDanmakuLiveDouyuDanmakuProviderNew();

  Future<LiveDanmuItem?> receive({required LiveDanmuConnection connection});

  Future<bool> supportsUrl({required String url});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LiveHuyaDanmakuProvider>>
abstract class LiveHuyaDanmakuProvider implements RustOpaqueInterface {
  Future<LiveDanmuConnection> connect({
    required String roomId,
    String? cookies,
    String? danmakuData,
  });

  Future<void> disconnect({required LiveDanmuConnection connection});

  Future<String?> extractRoomId({required String url});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<LiveHuyaDanmakuProvider> newInstance() =>
      RustLib.instance.api.crateApiDanmakuLiveHuyaDanmakuProviderNew();

  Future<LiveDanmuItem?> receive({required LiveDanmuConnection connection});

  Future<bool> supportsUrl({required String url});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LiveTwitchDanmakuProvider>>
abstract class LiveTwitchDanmakuProvider implements RustOpaqueInterface {
  Future<LiveDanmuConnection> connect({
    required String roomId,
    String? cookies,
    String? danmakuData,
  });

  Future<void> disconnect({required LiveDanmuConnection connection});

  Future<String?> extractRoomId({required String url});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<LiveTwitchDanmakuProvider> newInstance() =>
      RustLib.instance.api.crateApiDanmakuLiveTwitchDanmakuProviderNew();

  Future<LiveDanmuItem?> receive({required LiveDanmuConnection connection});

  Future<bool> supportsUrl({required String url});
}
