// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SliveBilibiliExtractor>>
abstract class SliveBilibiliExtractor implements RustOpaqueInterface {
  Future<String?> extractRoomId({required String url});

  Future<List<SliveCategory>> getCategories();

  Future<SliveCategoryResult> getCategoryRooms({
    required SliveSubCategory category,
    required int page,
  });

  Future<bool> getLiveStatus({required String roomId});

  Future<List<SlivePlayQuality>> getPlayQualities({
    required SliveRoomDetail detail,
  });

  Future<SlivePlayUrl> getPlayUrls({
    required SliveRoomDetail detail,
    required SlivePlayQuality quality,
  });

  Future<SliveCategoryResult> getRecommendRooms({required int page});

  Future<SliveRoomDetail> getRoomDetail({required String roomId});

  Future<List<SliveSuperChatMessage>> getSuperChatMessages({
    required String roomId,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SliveBilibiliExtractor> newInstance() =>
      RustLib.instance.api.crateApiExtractorSliveBilibiliExtractorNew();

  Future<SliveSearchAnchorResult> searchAnchors({
    required String keyword,
    required int page,
  });

  Future<SliveSearchRoomResult> searchRooms({
    required String keyword,
    required int page,
  });

  Future<void> setCookies({required String cookies});

  Future<bool> supportsUrl({required String url});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SliveDouyinExtractor>>
abstract class SliveDouyinExtractor implements RustOpaqueInterface {
  Future<String?> extractRoomId({required String url});

  Future<List<SliveCategory>> getCategories();

  Future<SliveCategoryResult> getCategoryRooms({
    required SliveSubCategory category,
    required int page,
  });

  Future<bool> getLiveStatus({required String roomId});

  Future<List<SlivePlayQuality>> getPlayQualities({
    required SliveRoomDetail detail,
  });

  Future<SlivePlayUrl> getPlayUrls({
    required SliveRoomDetail detail,
    required SlivePlayQuality quality,
  });

  Future<SliveCategoryResult> getRecommendRooms({required int page});

  Future<SliveRoomDetail> getRoomDetail({required String roomId});

  Future<List<SliveSuperChatMessage>> getSuperChatMessages({
    required String roomId,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SliveDouyinExtractor> newInstance() =>
      RustLib.instance.api.crateApiExtractorSliveDouyinExtractorNew();

  Future<SliveSearchAnchorResult> searchAnchors({
    required String keyword,
    required int page,
  });

  Future<SliveSearchRoomResult> searchRooms({
    required String keyword,
    required int page,
  });

  Future<void> setCookies({required String cookies});

  Future<bool> supportsUrl({required String url});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SliveDouyuExtractor>>
abstract class SliveDouyuExtractor implements RustOpaqueInterface {
  Future<String?> extractRoomId({required String url});

  Future<List<SliveCategory>> getCategories();

  Future<SliveCategoryResult> getCategoryRooms({
    required SliveSubCategory category,
    required int page,
  });

  Future<bool> getLiveStatus({required String roomId});

  Future<List<SlivePlayQuality>> getPlayQualities({
    required SliveRoomDetail detail,
  });

  Future<SlivePlayUrl> getPlayUrls({
    required SliveRoomDetail detail,
    required SlivePlayQuality quality,
  });

  Future<SliveCategoryResult> getRecommendRooms({required int page});

  Future<SliveRoomDetail> getRoomDetail({required String roomId});

  Future<List<SliveSuperChatMessage>> getSuperChatMessages({
    required String roomId,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SliveDouyuExtractor> newInstance() =>
      RustLib.instance.api.crateApiExtractorSliveDouyuExtractorNew();

  Future<SliveSearchAnchorResult> searchAnchors({
    required String keyword,
    required int page,
  });

  Future<SliveSearchRoomResult> searchRooms({
    required String keyword,
    required int page,
  });

  Future<void> setCookies({required String cookies});

  Future<bool> supportsUrl({required String url});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SliveHuyaExtractor>>
abstract class SliveHuyaExtractor implements RustOpaqueInterface {
  Future<String?> extractRoomId({required String url});

  Future<List<SliveCategory>> getCategories();

  Future<SliveCategoryResult> getCategoryRooms({
    required SliveSubCategory category,
    required int page,
  });

  Future<bool> getLiveStatus({required String roomId});

  Future<List<SlivePlayQuality>> getPlayQualities({
    required SliveRoomDetail detail,
  });

  Future<SlivePlayUrl> getPlayUrls({
    required SliveRoomDetail detail,
    required SlivePlayQuality quality,
  });

  Future<SliveCategoryResult> getRecommendRooms({required int page});

  Future<SliveRoomDetail> getRoomDetail({required String roomId});

  Future<List<SliveSuperChatMessage>> getSuperChatMessages({
    required String roomId,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SliveHuyaExtractor> newInstance() =>
      RustLib.instance.api.crateApiExtractorSliveHuyaExtractorNew();

  Future<SliveSearchAnchorResult> searchAnchors({
    required String keyword,
    required int page,
  });

  Future<SliveSearchRoomResult> searchRooms({
    required String keyword,
    required int page,
  });

  Future<void> setCookies({required String cookies});

  /// Set a custom User-Agent for Huya HTTP requests (e.g. HYSDK_UA).
  Future<void> setSdkUa({required String ua});

  Future<bool> supportsUrl({required String url});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SliveTwitchExtractor>>
abstract class SliveTwitchExtractor implements RustOpaqueInterface {
  Future<String?> extractRoomId({required String url});

  Future<List<SliveCategory>> getCategories();

  Future<SliveCategoryResult> getCategoryRooms({
    required SliveSubCategory category,
    required int page,
  });

  Future<bool> getLiveStatus({required String roomId});

  Future<List<SlivePlayQuality>> getPlayQualities({
    required SliveRoomDetail detail,
  });

  Future<SlivePlayUrl> getPlayUrls({
    required SliveRoomDetail detail,
    required SlivePlayQuality quality,
  });

  Future<SliveCategoryResult> getRecommendRooms({required int page});

  Future<SliveRoomDetail> getRoomDetail({required String roomId});

  Future<List<SliveSuperChatMessage>> getSuperChatMessages({
    required String roomId,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SliveTwitchExtractor> newInstance() =>
      RustLib.instance.api.crateApiExtractorSliveTwitchExtractorNew();

  Future<SliveSearchAnchorResult> searchAnchors({
    required String keyword,
    required int page,
  });

  Future<SliveSearchRoomResult> searchRooms({
    required String keyword,
    required int page,
  });

  Future<void> setCookies({required String cookies});

  Future<bool> supportsUrl({required String url});
}
