// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LiveBilibiliExtractor>>
abstract class LiveBilibiliExtractor implements RustOpaqueInterface {
  Future<String?> extractRoomId({required String url});

  Future<List<LiveCategory>> getCategories();

  Future<LiveCategoryResult> getCategoryRooms({
    required LiveSubCategory category,
    required int page,
  });

  Future<bool> getLiveStatus({required String roomId});

  Future<List<LivePlayQuality>> getPlayQualities({
    required LiveRoomDetail detail,
  });

  Future<LivePlayUrl> getPlayUrls({
    required LiveRoomDetail detail,
    required LivePlayQuality quality,
  });

  Future<LiveCategoryResult> getRecommendRooms({required int page});

  Future<LiveRoomDetail> getRoomDetail({required String roomId});

  Future<List<LiveSuperChatMessage>> getSuperChatMessages({
    required String roomId,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<LiveBilibiliExtractor> newInstance() =>
      RustLib.instance.api.crateApiExtractorLiveBilibiliExtractorNew();

  Future<LiveSearchAnchorResult> searchAnchors({
    required String keyword,
    required int page,
  });

  Future<LiveSearchRoomResult> searchRooms({
    required String keyword,
    required int page,
  });

  Future<void> setCookies({required String cookies});

  Future<bool> supportsUrl({required String url});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LiveDouyinExtractor>>
abstract class LiveDouyinExtractor implements RustOpaqueInterface {
  Future<String?> extractRoomId({required String url});

  Future<List<LiveCategory>> getCategories();

  Future<LiveCategoryResult> getCategoryRooms({
    required LiveSubCategory category,
    required int page,
  });

  Future<bool> getLiveStatus({required String roomId});

  Future<List<LivePlayQuality>> getPlayQualities({
    required LiveRoomDetail detail,
  });

  Future<LivePlayUrl> getPlayUrls({
    required LiveRoomDetail detail,
    required LivePlayQuality quality,
  });

  Future<LiveCategoryResult> getRecommendRooms({required int page});

  Future<LiveRoomDetail> getRoomDetail({required String roomId});

  Future<List<LiveSuperChatMessage>> getSuperChatMessages({
    required String roomId,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<LiveDouyinExtractor> newInstance() =>
      RustLib.instance.api.crateApiExtractorLiveDouyinExtractorNew();

  Future<LiveSearchAnchorResult> searchAnchors({
    required String keyword,
    required int page,
  });

  Future<LiveSearchRoomResult> searchRooms({
    required String keyword,
    required int page,
  });

  Future<void> setCookies({required String cookies});

  Future<bool> supportsUrl({required String url});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LiveDouyuExtractor>>
abstract class LiveDouyuExtractor implements RustOpaqueInterface {
  Future<String?> extractRoomId({required String url});

  Future<List<LiveCategory>> getCategories();

  Future<LiveCategoryResult> getCategoryRooms({
    required LiveSubCategory category,
    required int page,
  });

  Future<bool> getLiveStatus({required String roomId});

  Future<List<LivePlayQuality>> getPlayQualities({
    required LiveRoomDetail detail,
  });

  Future<LivePlayUrl> getPlayUrls({
    required LiveRoomDetail detail,
    required LivePlayQuality quality,
  });

  Future<LiveCategoryResult> getRecommendRooms({required int page});

  Future<LiveRoomDetail> getRoomDetail({required String roomId});

  Future<List<LiveSuperChatMessage>> getSuperChatMessages({
    required String roomId,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<LiveDouyuExtractor> newInstance() =>
      RustLib.instance.api.crateApiExtractorLiveDouyuExtractorNew();

  Future<LiveSearchAnchorResult> searchAnchors({
    required String keyword,
    required int page,
  });

  Future<LiveSearchRoomResult> searchRooms({
    required String keyword,
    required int page,
  });

  Future<void> setCookies({required String cookies});

  Future<bool> supportsUrl({required String url});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LiveHuyaExtractor>>
abstract class LiveHuyaExtractor implements RustOpaqueInterface {
  Future<String?> extractRoomId({required String url});

  Future<List<LiveCategory>> getCategories();

  Future<LiveCategoryResult> getCategoryRooms({
    required LiveSubCategory category,
    required int page,
  });

  Future<bool> getLiveStatus({required String roomId});

  Future<List<LivePlayQuality>> getPlayQualities({
    required LiveRoomDetail detail,
  });

  Future<LivePlayUrl> getPlayUrls({
    required LiveRoomDetail detail,
    required LivePlayQuality quality,
  });

  Future<LiveCategoryResult> getRecommendRooms({required int page});

  Future<LiveRoomDetail> getRoomDetail({required String roomId});

  Future<List<LiveSuperChatMessage>> getSuperChatMessages({
    required String roomId,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<LiveHuyaExtractor> newInstance() =>
      RustLib.instance.api.crateApiExtractorLiveHuyaExtractorNew();

  Future<LiveSearchAnchorResult> searchAnchors({
    required String keyword,
    required int page,
  });

  Future<LiveSearchRoomResult> searchRooms({
    required String keyword,
    required int page,
  });

  Future<void> setCookies({required String cookies});

  /// Set a custom User-Agent for Huya HTTP requests (e.g. HYSDK_UA).
  Future<void> setSdkUa({required String ua});

  Future<bool> supportsUrl({required String url});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LiveTwitchExtractor>>
abstract class LiveTwitchExtractor implements RustOpaqueInterface {
  Future<String?> extractRoomId({required String url});

  Future<List<LiveCategory>> getCategories();

  Future<LiveCategoryResult> getCategoryRooms({
    required LiveSubCategory category,
    required int page,
  });

  Future<bool> getLiveStatus({required String roomId});

  Future<List<LivePlayQuality>> getPlayQualities({
    required LiveRoomDetail detail,
  });

  Future<LivePlayUrl> getPlayUrls({
    required LiveRoomDetail detail,
    required LivePlayQuality quality,
  });

  Future<LiveCategoryResult> getRecommendRooms({required int page});

  Future<LiveRoomDetail> getRoomDetail({required String roomId});

  Future<List<LiveSuperChatMessage>> getSuperChatMessages({
    required String roomId,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<LiveTwitchExtractor> newInstance() =>
      RustLib.instance.api.crateApiExtractorLiveTwitchExtractorNew();

  Future<LiveSearchAnchorResult> searchAnchors({
    required String keyword,
    required int page,
  });

  Future<LiveSearchRoomResult> searchRooms({
    required String keyword,
    required int page,
  });

  Future<void> setCookies({required String cookies});

  Future<bool> supportsUrl({required String url});
}
