// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `danmu_type_to_message_type`, `parse_hex_color`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

class SliveAnchorItem {
  final String roomId;
  final String avatar;
  final String userName;
  final bool liveStatus;

  const SliveAnchorItem({
    required this.roomId,
    required this.avatar,
    required this.userName,
    required this.liveStatus,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      avatar.hashCode ^
      userName.hashCode ^
      liveStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SliveAnchorItem &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          avatar == other.avatar &&
          userName == other.userName &&
          liveStatus == other.liveStatus;
}

class SliveCategory {
  final String id;
  final String name;
  final List<SliveSubCategory> children;

  const SliveCategory({
    required this.id,
    required this.name,
    required this.children,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ children.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SliveCategory &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          children == other.children;
}

class SliveCategoryResult {
  final bool hasMore;
  final List<SliveRoomItem> items;

  const SliveCategoryResult({required this.hasMore, required this.items});

  @override
  int get hashCode => hasMore.hashCode ^ items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SliveCategoryResult &&
          runtimeType == other.runtimeType &&
          hasMore == other.hasMore &&
          items == other.items;
}

/// Mirrors `LiveMessage` superChat variant — kept as a separate type because
/// frb does not support `dynamic` fields, so the super-chat payload is typed.
class SliveDanmuControlEvent {
  final String kind;
  final String? message;
  final String? title;
  final String? category;
  final String? parentCategory;

  const SliveDanmuControlEvent({
    required this.kind,
    this.message,
    this.title,
    this.category,
    this.parentCategory,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      message.hashCode ^
      title.hashCode ^
      category.hashCode ^
      parentCategory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SliveDanmuControlEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message &&
          title == other.title &&
          category == other.category &&
          parentCategory == other.parentCategory;
}

@freezed
sealed class SliveDanmuItem with _$SliveDanmuItem {
  const SliveDanmuItem._();

  const factory SliveDanmuItem.message(SliveMessage field0) =
      SliveDanmuItem_Message;
  const factory SliveDanmuItem.superChat(SliveSuperChatMessage field0) =
      SliveDanmuItem_SuperChat;
  const factory SliveDanmuItem.control(SliveDanmuControlEvent field0) =
      SliveDanmuItem_Control;
}

/// A single key-value entry for bridging `Map<String, String>`.
class SliveMapEntry {
  final String key;
  final String value;

  const SliveMapEntry({required this.key, required this.value});

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SliveMapEntry &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}

/// Mirrors `LiveMessage` from the reference.
class SliveMessage {
  final SliveMessageType messageType;
  final String userName;
  final String message;

  /// JSON-serialized data (e.g. online count as string).
  final String? data;
  final SliveMessageColor color;

  const SliveMessage({
    required this.messageType,
    required this.userName,
    required this.message,
    this.data,
    required this.color,
  });

  @override
  int get hashCode =>
      messageType.hashCode ^
      userName.hashCode ^
      message.hashCode ^
      data.hashCode ^
      color.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SliveMessage &&
          runtimeType == other.runtimeType &&
          messageType == other.messageType &&
          userName == other.userName &&
          message == other.message &&
          data == other.data &&
          color == other.color;
}

/// Mirrors `LiveMessageColor` from the reference.
class SliveMessageColor {
  final int r;
  final int g;
  final int b;

  const SliveMessageColor({required this.r, required this.g, required this.b});

  @override
  int get hashCode => r.hashCode ^ g.hashCode ^ b.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SliveMessageColor &&
          runtimeType == other.runtimeType &&
          r == other.r &&
          g == other.g &&
          b == other.b;
}

/// Mirrors `LiveMessageType` enum from the reference.
enum SliveMessageType { chat, gift, online, superChat }

class SlivePlayQuality {
  final String quality;
  final String data;
  final int sort;

  const SlivePlayQuality({
    required this.quality,
    required this.data,
    required this.sort,
  });

  @override
  int get hashCode => quality.hashCode ^ data.hashCode ^ sort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SlivePlayQuality &&
          runtimeType == other.runtimeType &&
          quality == other.quality &&
          data == other.data &&
          sort == other.sort;
}

class SlivePlayUrl {
  final List<String> urls;
  final List<SliveMapEntry>? headers;

  const SlivePlayUrl({required this.urls, this.headers});

  @override
  int get hashCode => urls.hashCode ^ headers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SlivePlayUrl &&
          runtimeType == other.runtimeType &&
          urls == other.urls &&
          headers == other.headers;
}

class SliveRoomDetail {
  final String roomId;
  final String title;
  final String cover;
  final String userName;
  final String userAvatar;
  final PlatformInt64 online;
  final String? introduction;
  final String? notice;
  final bool status;

  /// Platform-specific data serialized as JSON string.
  final String? data;

  /// Danmaku connection data serialized as JSON string.
  final String? danmakuData;
  final String url;
  final bool isRecord;

  const SliveRoomDetail({
    required this.roomId,
    required this.title,
    required this.cover,
    required this.userName,
    required this.userAvatar,
    required this.online,
    this.introduction,
    this.notice,
    required this.status,
    this.data,
    this.danmakuData,
    required this.url,
    required this.isRecord,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      title.hashCode ^
      cover.hashCode ^
      userName.hashCode ^
      userAvatar.hashCode ^
      online.hashCode ^
      introduction.hashCode ^
      notice.hashCode ^
      status.hashCode ^
      data.hashCode ^
      danmakuData.hashCode ^
      url.hashCode ^
      isRecord.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SliveRoomDetail &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          title == other.title &&
          cover == other.cover &&
          userName == other.userName &&
          userAvatar == other.userAvatar &&
          online == other.online &&
          introduction == other.introduction &&
          notice == other.notice &&
          status == other.status &&
          data == other.data &&
          danmakuData == other.danmakuData &&
          url == other.url &&
          isRecord == other.isRecord;
}

class SliveRoomItem {
  final String roomId;
  final String title;
  final String cover;
  final String userName;
  final PlatformInt64 online;

  const SliveRoomItem({
    required this.roomId,
    required this.title,
    required this.cover,
    required this.userName,
    required this.online,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      title.hashCode ^
      cover.hashCode ^
      userName.hashCode ^
      online.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SliveRoomItem &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          title == other.title &&
          cover == other.cover &&
          userName == other.userName &&
          online == other.online;
}

class SliveSearchAnchorResult {
  final bool hasMore;
  final List<SliveAnchorItem> items;

  const SliveSearchAnchorResult({required this.hasMore, required this.items});

  @override
  int get hashCode => hasMore.hashCode ^ items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SliveSearchAnchorResult &&
          runtimeType == other.runtimeType &&
          hasMore == other.hasMore &&
          items == other.items;
}

class SliveSearchRoomResult {
  final bool hasMore;
  final List<SliveRoomItem> items;

  const SliveSearchRoomResult({required this.hasMore, required this.items});

  @override
  int get hashCode => hasMore.hashCode ^ items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SliveSearchRoomResult &&
          runtimeType == other.runtimeType &&
          hasMore == other.hasMore &&
          items == other.items;
}

class SliveSubCategory {
  final String id;
  final String name;
  final String parentId;
  final String? pic;

  const SliveSubCategory({
    required this.id,
    required this.name,
    required this.parentId,
    this.pic,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ parentId.hashCode ^ pic.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SliveSubCategory &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          parentId == other.parentId &&
          pic == other.pic;
}

class SliveSuperChatMessage {
  final String userName;
  final String face;
  final String message;
  final int price;

  /// Unix timestamp in milliseconds.
  final PlatformInt64 startTime;

  /// Unix timestamp in milliseconds.
  final PlatformInt64 endTime;
  final String backgroundColor;
  final String backgroundBottomColor;

  const SliveSuperChatMessage({
    required this.userName,
    required this.face,
    required this.message,
    required this.price,
    required this.startTime,
    required this.endTime,
    required this.backgroundColor,
    required this.backgroundBottomColor,
  });

  @override
  int get hashCode =>
      userName.hashCode ^
      face.hashCode ^
      message.hashCode ^
      price.hashCode ^
      startTime.hashCode ^
      endTime.hashCode ^
      backgroundColor.hashCode ^
      backgroundBottomColor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SliveSuperChatMessage &&
          runtimeType == other.runtimeType &&
          userName == other.userName &&
          face == other.face &&
          message == other.message &&
          price == other.price &&
          startTime == other.startTime &&
          endTime == other.endTime &&
          backgroundColor == other.backgroundColor &&
          backgroundBottomColor == other.backgroundBottomColor;
}
