// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';
part 'types.g.dart';

// These functions are ignored because they are not marked as `pub`: `danmu_type_to_message_type`, `parse_hex_color`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

class LiveAnchorItem {
  final String roomId;
  final String avatar;
  final String userName;
  final bool liveStatus;

  const LiveAnchorItem({
    required this.roomId,
    required this.avatar,
    required this.userName,
    required this.liveStatus,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      avatar.hashCode ^
      userName.hashCode ^
      liveStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveAnchorItem &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          avatar == other.avatar &&
          userName == other.userName &&
          liveStatus == other.liveStatus;
}

class LiveCategory {
  final String id;
  final String name;
  final List<LiveSubCategory> children;

  const LiveCategory({
    required this.id,
    required this.name,
    required this.children,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ children.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveCategory &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          children == other.children;
}

class LiveCategoryResult {
  final bool hasMore;
  final List<LiveRoomItem> items;

  const LiveCategoryResult({required this.hasMore, required this.items});

  @override
  int get hashCode => hasMore.hashCode ^ items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveCategoryResult &&
          runtimeType == other.runtimeType &&
          hasMore == other.hasMore &&
          items == other.items;
}

/// Mirrors `LiveMessage` superChat variant — kept as a separate type because
/// frb does not support `dynamic` fields, so the super-chat payload is typed.
class LiveDanmuControlEvent {
  final String kind;
  final String? message;
  final String? title;
  final String? category;
  final String? parentCategory;

  const LiveDanmuControlEvent({
    required this.kind,
    this.message,
    this.title,
    this.category,
    this.parentCategory,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      message.hashCode ^
      title.hashCode ^
      category.hashCode ^
      parentCategory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveDanmuControlEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message &&
          title == other.title &&
          category == other.category &&
          parentCategory == other.parentCategory;
}

@freezed
sealed class LiveDanmuItem with _$LiveDanmuItem {
  const LiveDanmuItem._();

  const factory LiveDanmuItem.message(LiveMessage field0) =
      LiveDanmuItem_Message;
  const factory LiveDanmuItem.control(LiveDanmuControlEvent field0) =
      LiveDanmuItem_Control;
}

/// Mirrors `DanmuMessage` from platforms-parser.
class LiveMessage {
  final String id;
  final String userId;
  final String userName;
  final String message;
  final LiveMessageColor color;

  /// Unix timestamp in milliseconds.
  final int timeMillis;
  final LiveMessageType messageType;

  /// Platform-specific metadata serialized as JSON string.
  final String? metadata;

  const LiveMessage({
    required this.id,
    required this.userId,
    required this.userName,
    required this.message,
    required this.color,
    required this.timeMillis,
    required this.messageType,
    this.metadata,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      userId.hashCode ^
      userName.hashCode ^
      message.hashCode ^
      color.hashCode ^
      timeMillis.hashCode ^
      messageType.hashCode ^
      metadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          userId == other.userId &&
          userName == other.userName &&
          message == other.message &&
          color == other.color &&
          timeMillis == other.timeMillis &&
          messageType == other.messageType &&
          metadata == other.metadata;
}

/// Mirrors `LiveMessageColor` from the reference.
class LiveMessageColor {
  final int r;
  final int g;
  final int b;

  const LiveMessageColor({required this.r, required this.g, required this.b});

  static LiveMessageColor fromInt({required int intColor}) => RustLib
      .instance
      .api
      .crateApiTypesLiveMessageColorFromInt(intColor: intColor);

  String toHex() =>
      RustLib.instance.api.crateApiTypesLiveMessageColorToHex(that: this);

  static LiveMessageColor white() =>
      RustLib.instance.api.crateApiTypesLiveMessageColorWhite();

  @override
  int get hashCode => r.hashCode ^ g.hashCode ^ b.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveMessageColor &&
          runtimeType == other.runtimeType &&
          r == other.r &&
          g == other.g &&
          b == other.b;
}

/// Arguments passed to the danmaku WebSocket after room detail is fetched.
/// Mirrors `LiveMessageType` enum from the reference.
enum LiveMessageType { chat, gift, online, superChat }

class LivePlayQuality {
  final String quality;
  final String data;
  final int sort;

  const LivePlayQuality({
    required this.quality,
    required this.data,
    required this.sort,
  });

  @override
  int get hashCode => quality.hashCode ^ data.hashCode ^ sort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LivePlayQuality &&
          runtimeType == other.runtimeType &&
          quality == other.quality &&
          data == other.data &&
          sort == other.sort;
}

class LivePlayUrl {
  final List<String> urls;
  final Map<String, String>? headers;

  const LivePlayUrl({required this.urls, this.headers});

  @override
  int get hashCode => urls.hashCode ^ headers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LivePlayUrl &&
          runtimeType == other.runtimeType &&
          urls == other.urls &&
          headers == other.headers;
}

class LiveRoomDetail {
  final String roomId;
  final String title;
  final String cover;
  final String userName;
  final String userAvatar;
  final int online;
  final String? introduction;
  final String? notice;
  final bool status;

  /// Platform-specific data serialized as JSON string.
  final String? data;

  /// Danmaku connection data serialized as JSON string.
  final String? danmakuData;
  final String url;
  final bool isRecord;

  const LiveRoomDetail({
    required this.roomId,
    required this.title,
    required this.cover,
    required this.userName,
    required this.userAvatar,
    required this.online,
    this.introduction,
    this.notice,
    required this.status,
    this.data,
    this.danmakuData,
    required this.url,
    required this.isRecord,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      title.hashCode ^
      cover.hashCode ^
      userName.hashCode ^
      userAvatar.hashCode ^
      online.hashCode ^
      introduction.hashCode ^
      notice.hashCode ^
      status.hashCode ^
      data.hashCode ^
      danmakuData.hashCode ^
      url.hashCode ^
      isRecord.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveRoomDetail &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          title == other.title &&
          cover == other.cover &&
          userName == other.userName &&
          userAvatar == other.userAvatar &&
          online == other.online &&
          introduction == other.introduction &&
          notice == other.notice &&
          status == other.status &&
          data == other.data &&
          danmakuData == other.danmakuData &&
          url == other.url &&
          isRecord == other.isRecord;
}

class LiveRoomItem {
  final String roomId;
  final String title;
  final String cover;
  final String userName;
  final int online;

  const LiveRoomItem({
    required this.roomId,
    required this.title,
    required this.cover,
    required this.userName,
    required this.online,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      title.hashCode ^
      cover.hashCode ^
      userName.hashCode ^
      online.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveRoomItem &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          title == other.title &&
          cover == other.cover &&
          userName == other.userName &&
          online == other.online;
}

class LiveSearchAnchorResult {
  final bool hasMore;
  final List<LiveAnchorItem> items;

  const LiveSearchAnchorResult({required this.hasMore, required this.items});

  @override
  int get hashCode => hasMore.hashCode ^ items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveSearchAnchorResult &&
          runtimeType == other.runtimeType &&
          hasMore == other.hasMore &&
          items == other.items;
}

class LiveSearchRoomResult {
  final bool hasMore;
  final List<LiveRoomItem> items;

  const LiveSearchRoomResult({required this.hasMore, required this.items});

  @override
  int get hashCode => hasMore.hashCode ^ items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveSearchRoomResult &&
          runtimeType == other.runtimeType &&
          hasMore == other.hasMore &&
          items == other.items;
}

class LiveSubCategory {
  final String id;
  final String name;
  final String parentId;
  final String? pic;

  const LiveSubCategory({
    required this.id,
    required this.name,
    required this.parentId,
    this.pic,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ parentId.hashCode ^ pic.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveSubCategory &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          parentId == other.parentId &&
          pic == other.pic;
}

@freezed
sealed class LiveSuperChatMessage with _$LiveSuperChatMessage {
  const factory LiveSuperChatMessage({
    required String userName,
    required String face,
    required String message,
    required int price,
    required int startTime,
    required int endTime,
    required String backgroundColor,
    required String backgroundBottomColor,
  }) = _LiveSuperChatMessage;

  factory LiveSuperChatMessage.fromJson(Map<String, dynamic> json) =>
      _$LiveSuperChatMessageFromJson(json);
}
